---
- name: backup ios routers/switch
  hosts: routers
  become: true
  vars:
   project_path: "{{ lookup('env', 'PWD') }}"
   network_backup_file:  /tmp/
  tasks:
    - command: "ls {{ project_path }}"
      register: ls_output

    - debug: var=ls_output

    - name: backing up running config
      ios_config:
         backup: yes
      register: backup_output

    - set_fact:
        temp_backup_file: "{{ backup_output.backup_path }}"

    - name: Copy the temp to the destination
      copy:
        src: "{{ temp_backup_file }}"
        dest: "{{ network_backup_file }}"
      register: copy_result
      connection: ssh
      become: yes

    - command: "ls {{ project_path }}"
      register: ls_post_output

    - debug: var=ls_post_output
    
    - debug: var=backup_output

    - debug: var=copy_result
