---
- name: backup ios routers/switch
  hosts: routers
  connection: network_cli
  vars:
    ansible_network_os: ios
  #become: yes
  vars:
   network_backup_file:  /tmp/
  gather_facts: false
  tasks:
    - name: backing up running config
      ios_config:
         backup: yes
      register: backup_output

    - set_fact:
         router_backup_value: "{{ backup_output.backup_path }}"
         cacheable: yes
      connection: ssh
           
    - debug:
         var: hostvars[inventory_hostname]
      connection: local
    
    - command: hostname -i
      register: output_ip
      delegate_to: localhost

    - name: Copy the temp to the destination
      copy:
        src: "{{ router_backup_value }}"
        dest: "{{ network_backup_file }}"
      register: copy_result
      delegate_to: "{{ output_ip.stdout_lines[0] }}"
      
