---
- name: backup ios routers/switch
  hosts: routers
  connection: network_cli
  vars:
    ansible_network_os: ios
  vars:
   network_backup_file:  /tmp/
  gather_facts: false
  tasks:
    - name: backing up running config
      ios_config:
         backup: yes
      register: backup_output

    - set_fact:
         router_backup_value: "{{ backup_output.backup_path }}"
      connection: local
      
    - debug:
         var: hostvars[inventory_hostname]
         
    - debug:
         var: hostvars[inventory_hostname]
      connection: local

    - name: Copy the temp to the destination
      copy:
        src: "{{ hostvars[inventory_hostname][router_backup_value] }}"
        dest: "{{ network_backup_file }}"
      register: copy_result
      connection: local
      
      
