---
- name: backup ios routers/switch
  hosts: routers
  vars:
    ansible_network_os: ios
  vars:
   network_backup_file:  /tmp/
  gather_facts: false
  tasks:
    - name: backing up running config
      ios_config:
         backup: yes
      register: backup_output
      connection: network_cli

    - set_fact:
        router_backup_value: "{{ backup_output.backup_path }}"
        cacheable: yes
      connection: local

    - name: Copy the temp to the destination
      copy:
        src: "{{ backup_output.backup_path }}"
        dest: "{{ network_backup_file }}"
      register: copy_result
      connection: local
      
      
