---
- name: backup ios routers/switch
  hosts: routers
  connection: network_cli
  vars:
    ansible_network_os: ios
  vars:
   network_backup_file:  /tmp/
  tasks:
    - name: backing up running config
      ios_config:
         backup: yes
      register: backup_output

    - set_fact:
        router_backup_value: "{{ backup_output.backup_path }}"
        cacheable: yes

    - name: Copy the temp to the destination
      copy:
        src: "{{ backup_output.backup_path }}"
        dest: "{{ network_backup_file }}"
      register: copy_result
      delegate_to: 192.168.21.42
      
      
