---
- name: backup ios routers/switch
  hosts: all
  gather_facts: false
  vars:
   project_path: "{{ lookup('env', 'PWD') }}"
  tasks:
          #- command: hostname
          # register: host_output

      #- debug: var=host_output
    - command: "ls {{ project_path }}"
      register: ls_output

    - debug: var=ls_output

    - name: backing up running config
      ios_config:
         backup: yes
         backup_options:
           dir_path: /var/lib/awx
      register: backup_output

    - command: "ls {{ project_path }}"
      register: ls_post_output

    - debug: var=ls_post_output


    - debug: var=backup_output

